# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: weather.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'weather.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rweather.proto\x12\x07weather\"&\n\x0eWeatherRequest\x12\x14\n\x0ctemperatures\x18\x01 \x03(\x02\"<\n\x0fWeatherResponse\x12\x0f\n\x07\x61verage\x18\x01 \x01(\x02\x12\x0b\n\x03min\x18\x02 \x01(\x02\x12\x0b\n\x03max\x18\x03 \x01(\x02\x32X\n\x0eWeatherService\x12\x46\n\x0fGetWeatherStats\x12\x17.weather.WeatherRequest\x1a\x18.weather.WeatherResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weather_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WEATHERREQUEST']._serialized_start=26
  _globals['_WEATHERREQUEST']._serialized_end=64
  _globals['_WEATHERRESPONSE']._serialized_start=66
  _globals['_WEATHERRESPONSE']._serialized_end=126
  _globals['_WEATHERSERVICE']._serialized_start=128
  _globals['_WEATHERSERVICE']._serialized_end=216
# @@protoc_insertion_point(module_scope)
